export const logs = [
  {
    logs_id: 0,
    time_stamp: '2024-04-30T12:34:56.789Z',
    user_name: 'Duan LV',
    update: false,
    create: false,
    delete: false,
    control: true,
    des_device_id: 0,
    control_type: 'LGT',
    control_time: 20,
    period_time: 2,
    pause_time: 1,
    status: 'success'
  },
  {
    logs_id: 1,
    time_stamp: '2024-05-02T23:45:01.234Z',
    user_name: 'Trang Ha',
    update: false,
    create: false,
    delete: false,
    control: true,
    des_device_id: 0,
    control_type: 'VBR',
    control_time: 20,
    period_time: 2,
    pause_time: 1,
    status: 'error'
  },
  {
    logs_id: 2,
    time_stamp: '2024-05-07T14:46:25.000Z',
    user_name: 'Hien Hoang',
    update: false,
    create: false,
    delete: false,
    control: true,
    des_device_id: 0,
    control_type: 'VLG',
    control_time: 20,
    period_time: 2,
    pause_time: 1,
    status: 'success'
  },
  {
    logs_id: 3,
    time_stamp: '2024-05-07T16:05:25.000Z',
    user_name: 'Le Duan',
    update: false,
    create: false,
    delete: false,
    control: true,
    des_device_id: 0,
    control_type: 'VBR',
    control_time: 20,
    period_time: 2,
    pause_time: 1,
    status: 'success'
  },
  {
    logs_id: 4,
    time_stamp: '2023-05-07T17:05:25.000Z',
    user_name: 'Duong Hai',
    update: true,
    create: false,
    delete: false,
    control: false,
    des_device_id: 0,
    control_type: '',
    control_time: 0,
    period_time: 0,
    pause_time: 0,
    status: 'success'
  },
  {
    logs_id: 5,
    time_stamp: '2024-04-01T17:03:15.000Z',
    user_name: 'Hien Hoang',
    update: false,
    create: true,
    delete: false,
    control: false,
    des_device_id: 0,
    control_type: '',
    control_time: 0,
    period_time: 0,
    pause_time: 0,
    status: 'success'
  },
  {
    logs_id: 6,
    time_stamp: '2023-05-07T17:05:25.000Z',
    user_name: 'Hoa Khanh',
    update: false,
    create: false,
    delete: true,
    control: false,
    des_device_id: 0,
    control_type: '',
    control_time: 0,
    period_time: 0,
    pause_time: 0,
    status: 'error'
  }
]
